approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@stylistic/eslint-plugin@2.13.0":
    peerDependencies:
      typescript: ">=4.8.4 <6.1.0"
